Class {
	#name : #NoEffectBox,
	#superclass : #Object,
	#category : #'IngSoft2-Model'
}

{ #category : #'Instance creation' }
NoEffectBox class >> initializeNew [

	^ self new initializeNew
]

{ #category : #Effect }
NoEffectBox >> changePolarity [
	
]

{ #category : #Effect }
NoEffectBox >> effect: aGame [

	
]

{ #category : #Initialization }
NoEffectBox >> initializeNew [
]
